FROM apache/airflow:2.7.1-python3.9@sha256:fadcd177ae17f604f587aa8761bbd398685e00d379a2da7eab1c4ca4cb476f49
USER root

# Install OpenJDK-11
RUN apt update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y ant && \
    apt-get install -y procps && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-arm64
RUN export JAVA_HOME

USER airflow

RUN pip install \
    lxml \
    pyspark==3.3.2 \
    apache-airflow-providers-apache-spark \
    requests \
    pandas

COPY --chown=airflow:root ./dags /opt/airflow/dags

RUN pip install \
    python-dotenv==0.20.0 \
    kafka-python==2.0.2 \
    faker==18.9.0

RUN curl https://jdbc.postgresql.org/download/postgresql-42.2.18.jar -o /opt/postgresql-42.2.18.jar
RUN curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.1.1/kafka-clients-2.1.1.jar -o /opt/kafka-clients-2.1.1.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.2/spark-sql-kafka-0-10_2.12-3.3.2.jar -o /opt/spark-sql-kafka-0-10_2.12-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-0-10_2.12/3.3.2/spark-streaming-kafka-0-10_2.12-3.3.2.jar -o /opt/spark-streaming-kafka-0-10_2.12-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.2/spark-token-provider-kafka-0-10_2.12-3.3.2.jar -o /opt/spark-token-provider-kafka-0-10_2.12-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar -o /opt/commons-pool2-2.11.1.jar